import type { Metadata } from 'next';
import {
  Fraunces,
  IBM_Plex_Sans,
  IBM_Plex_Sans_KR,
  IBM_Plex_Mono,
} from 'next/font/google';
import './globals.css';
import { Analytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
import ThemeShell from '@/components/ThemeShell';
import { SITE_URL } from '@/lib/site';

/* Type system — see DESIGN.md § Typography.

   Display  Fraunces (Latin only) — old-style serif with a little optical wonk.
   Everything else  IBM Plex Sans · Sans KR · Mono — one designed superfamily.

   Korean is served by exactly ONE webfont family, deliberately. Google's Korean
   faces ship ~2,500 glyphs split across ~94 unicode-range subsets, so a second
   Korean family would roughly double both the @font-face count and the bytes a
   Korean page pulls (measured: 157–393 KB per route for this one family, with
   preloading off — see the note on `korean` below, which is what keeps that
   number from being 1.8 MB). Plex Sans KR therefore does both display and body
   duty; Fraunces stays Latin-only and never triggers a Korean download. Korean
   headlines set in Plex Sans KR 600 sit beside Latin headlines in Fraunces —
   the two voices alternate by section, not inside a line, which is where a
   mixed pairing would actually show. */

const display = Fraunces({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-display',
  display: 'swap',
});

const body = IBM_Plex_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-body',
  display: 'swap',
});

// The single Korean face — resolves Korean glyphs for both type stacks.
//
// `preload: false` is load-bearing, and it is the one setting on this page that
// is worth more than every other byte decision here combined.
//
// Google splits its Korean faces into ~94 unicode-range subsets, so three
// weights of this family alone emit 282 @font-face rules. next/font preloads
// the whole set — `subsets: ['latin']` does not narrow it, measured — and a
// `<link rel=preload>` is unconditional: it defeats the very unicode-range
// mechanism that is supposed to keep a Korean page from downloading all of
// Korean. Measured on a cold cache, every route shipped 187 preload tags and
// pulled ~1.8 MB of woff2, roughly three quarters of the page's total weight.
//
// With preloading off the browser resolves the @font-face rules the ordinary
// way and fetches only the subsets the page's glyphs actually land in:
// ~12–44 files and 157–393 KB depending on the route, with the page total
// falling from ~2.4 MB to ~0.85 MB on the home page. `display: 'swap'` is what
// makes that safe — the fallback paints immediately and the real face swaps in.
const korean = IBM_Plex_Sans_KR({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-korean',
  display: 'swap',
  preload: false,
});

// 600 is worth its bytes even though the weight budget is otherwise tight.
// Measured: +32 KB on disk across five unicode-range subsets, of which a page
// actually downloads only `latin` — against the 150–330 KB a Korean weight
// would cost. It earns that by carrying every emphasised mono label: table
// headers, status chips, stat values, the Lab's whole data surface.
const mono = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-mono',
  display: 'swap',
});

export const metadata: Metadata = {
  title: {
    default: 'phorage — Collecting the Greenery',
    template: '%s | phorage',
  },
  description: '빛을 수집하고 세상을 분석합니다. 자연과 일상이 교차하는 지점을 기록하는 phorage studio.',
  metadataBase: new URL(SITE_URL),
  // Note: OG/Twitter images are auto-generated by src/app/opengraph-image.tsx
  // (file convention). Don't reference a static /og-image.png that doesn't exist.
  openGraph: {
    title: 'phorage — Collecting the Greenery',
    description: '빛을 수집하고 세상을 분석합니다. 자연과 일상이 교차하는 지점을 기록하는 phorage studio.',
    siteName: 'phorage',
    locale: 'ko_KR',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'phorage — Collecting the Greenery',
    description: '빛을 수집하고 세상을 분석합니다.',
  },
  robots: { index: true, follow: true },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="ko"
      className={`${display.variable} ${body.variable} ${korean.variable} ${mono.variable}`}
    >
      <ThemeShell>
        <a href="#main-content" className="skip-link">본문 바로가기</a>
        <Nav />
        <div id="main-content" className="flex-grow pt-[72px] md:pt-[88px]">
          {children}
        </div>
        <Footer />
        {/* 방문 통계와 실사용자 Core Web Vitals.

            /portfolio는 URL로만 건네는 페이지다 — 열렸는지, 어디까지 읽혔는지,
            인쇄 화면까지 갔는지 알 방법이 지금까지 없었다. 지원 후 팔로업에
            실제로 쓰는 정보다.

            Speed Insights를 같이 두는 이유는 폰트 preload를 들어낸 변경(홈
            2.4 MB → 0.85 MB)이 실험실 수치라서다. 현장에서 확인되지 않으면
            그냥 주장이다.

            둘 다 같은 오리진(`/_vercel/…`)에서 스크립트를 받고 같은 곳으로
            비콘을 보내므로 CSP를 손댈 필요가 없다. 쿠키도 쓰지 않는다. */}
        <Analytics />
        <SpeedInsights />
      </ThemeShell>
    </html>
  );
}
