services:
  frontend:
    image: node:20-alpine
    container_name: phorage_frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    # 설치 명령어는 빼고, 실행 명령어만 남깁니다.
    command: sh -c "npm install && npm run dev -- -p 3000 -H 0.0.0.0"

  backend:
    image: python:3.9-slim
    container_name: phorage_backend
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "8000:8000"
    command: sh -c "pip install fastapi uvicorn pandas && uvicorn main:app --host 0.0.0.0 --reload"