backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "albums"
    label: "앨범 관리"
    folder: "data/albums"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "앨범 제목", name: "title", widget: "string" }
      - { label: "앨범 커버 이미지", name: "cover", widget: "image" }
      - { label: "앨범 설명", name: "desc", widget: "text" }

  - name: "photos"
    label: "사진 관리"
    folder: "data/photos"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "사진 제목", name: "title", widget: "string" }
      - { label: "앨범 선택", name: "album", widget: "string" }
      - { label: "사진 파일", name: "src", widget: "image" }
      - { label: "촬영 장소", name: "location", widget: "string" }
      - { label: "촬영 연도", name: "year", widget: "string" }
      - { label: "카테고리(태그)", name: "categories", widget: "list" }